version: '3.7'

services:
  localstack:
    container_name: "my-project_localstack"
    image: localstack/localstack
    ports:
      - "4578:4566"
    environment:
      - SERVICES=apigateway,cloudwatchlogs,iam,dynamodb,lambda,sts
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  api:
    image: "my-project-api:latest"
    build: ./src/api
    user: "1000:1000"
    container_name: my-project_api
    restart: unless-stopped
    depends_on:
      - localstack
    environment:
      ASPNETCORE_ENVIRONMENT: production
      ENVIRONMENT_ID: docker
      PROJECT_ID: my-project
    ports:
      - '5232:80/tcp'

  www:
    container_name: 'my-project_www'
    image: 'node:lts-alpine'
    restart: unless-stopped
    volumes:
      - './src/www:/home/node/www'
    working_dir: /home/node/www
    entrypoint: "/bin/sh"
    command: 'run.docker.sh'
    environment:
      NODE_ENV: development
      ENVIRONMENT_ID: docker
    ports:
      - '3000:3000/tcp'
